# ECS 171 Homework 5
## by, Jeffrey Ugochukwu
### 1
Load the data from the provided .csv file into a pandas dataframe, it contains a list of 1200 bitstrings which each have a length of 16 bits. Call the dataset S. We call two bitstrings A and B equivalent (A∼B) if you can flip one bit at a time starting from A to produce a sequence of strings A,s1,s2,...,sn,B∈S that are all within the dataset to get the string B. Through this notion of equivalence, we may define an equivalence relation on this set of bit strings. Using agglomerative clustering with a tolerance on distance for early stopping, we can compute the number of equivalence classes by counting the number of clusters. In order to do this, which linkage rule should be used (single-linkage, complete-linkage, or average-linkage), which distance function should be used (Euclidiean distance, Manhattan distance, or cosine distance), and what should the threshold distance be? Explain why you would pick these parameters.

In [73]:
import pandas as pd
import sklearn 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import kneighbors_graph
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import seaborn as sns
sns.set()
#Importing Dataset
S = pd.read_csv("bitstrings.csv")
S

0  0.1  0.2  0.3  0.4  0.5  1  1.1  0.6  1.2  1.3  1.4  1.5  1.6  0.7  \
0     0    0    0    0    0    0  1    1    0    0    1    1    1    1    0   
1     0    0    0    0    0    0  0    1    0    0    1    1    1    1    0   
2     0    0    0    0    0    0  1    1    0    0    1    1    1    1    0   
3     0    0    0    0    0    1  1    1    0    0    1    1    1    1    0   
4     0    0    0    0    1    1  1    1    0    0    1    1    1    1    0   
...  ..  ...  ...  ...  ...  ... ..  ...  ...  ...  ...  ...  ...  ...  ...   
1194  1    1    0    1    1    1  1    1    1    0    0    0    1    1    1   
1195  1    1    0    1    1    1  1    1    1    0    0    0    1    1    1   
1196  1    1    0    1    1    1  1    1    1    1    0    0    1    1    1   
1197  1    1    0    1    1    1  1    1    1    1    1    1    1    1    1   
1198  1    0    0    1    1    1  1    1    1    1    1    0    1    1    1   

      0.8  
0       0  
1       0  
2       0  
3       0  
4       0  
...   ...  
1194    1  
1195    0  
1196    1  
1197    1  
1198    1  

[1199 rows x 16 columns]

I believe that we should use the single-linkage rule because we're checking individual bits to see how they're changing at a time. This would also mean that we would have to use Manhattan distance for this calculation since we have a high dimensionality of 16 bits and this can check the individual change per bit. Our threshold should be 1.0001 because the points given here range from 0 to 1, so finding the euclidean distance of this gives us the value of 1.0001 for the threshold.

### 2
Perform the clustering using the parameters you picked in Q1. How many equivalence classes (clusters) are there? Create a bar plot, showing the number of strings in each cluster.

In [64]:
#Single Linkage cluster
cluster = AgglomerativeClustering(n_clusters=None, affinity='manhattan', linkage='single', distance_threshold = 1.0001)
d = cluster.fit_predict(S)
d

array([7, 7, 7, ..., 2, 2, 2], dtype=int64)

In [65]:
#Labels of cluster
print(cluster.labels_)

[7 7 7 ... 2 2 2]


In [77]:
#Value counts
S.value_counts()

0  0.1  0.2  0.3  0.4  0.5  1  1.1  0.6  1.2  1.3  1.4  1.5  1.6  0.7  0.8
0  1    0    1    0    0    1  0    0    0    0    0    1    1    0    0      10
1  1    0    1    1    1    1  1    1    1    0    0    1    1    1    1       9
        1    1    0    0    1  1    0    1    0    1    1    1    1    1       8
0  1    0    0    0    1    1  1    0    1    0    1    0    0    0    1       8
1  0    0    1    1    0    0  0    1    1    0    0    1    0    0    1       7
                                                                              ..
0  1    0    1    1    1    0  1    0    0    1    0    1    1    1    0       1
                                                   1    1    0    1    0       1
                            1  0    0    0    1    0    0    0    1    0       1
                                                        1    0    0    0       1
1  1    1    1    1    1    1  1    1    1    1    0    1    1    1    1       1
Length: 784, dtype: int64

### 3
Using this clustering, determine if 0000001101111100∼1011101101111101. What about 1001111011001001∼1001111011000000? (You need to show that you used this clustering to determine the answer).

In [83]:
#Classification
cluster = AgglomerativeClustering(n_clusters=None, affinity='manhattan', linkage='single', distance_threshold = 1.0001)
d = cluster.fit_predict(S)
d

array([7, 7, 7, ..., 2, 2, 2], dtype=int64)

### 4
Redo the clustering on the dataset, but this time using both of the other linkage rules (keep everything else the same), and report the number of clusters for both. Is there any difference from the number of clusters you found in Q2? If so, explain why.

In [69]:
#Complete linkage
cluster2 = AgglomerativeClustering(n_clusters=None, affinity='manhattan', linkage='complete', distance_threshold = 1.0001)
d2 = cluster2.fit_predict(S)
d2

array([572, 572, 572, ..., 163, 284, 250], dtype=int64)

In [84]:
#Value counts
S.value_counts()

0  0.1  0.2  0.3  0.4  0.5  1  1.1  0.6  1.2  1.3  1.4  1.5  1.6  0.7  0.8
0  1    0    1    0    0    1  0    0    0    0    0    1    1    0    0      10
1  1    0    1    1    1    1  1    1    1    0    0    1    1    1    1       9
        1    1    0    0    1  1    0    1    0    1    1    1    1    1       8
0  1    0    0    0    1    1  1    0    1    0    1    0    0    0    1       8
1  0    0    1    1    0    0  0    1    1    0    0    1    0    0    1       7
                                                                              ..
0  1    0    1    1    1    0  1    0    0    1    0    1    1    1    0       1
                                                   1    1    0    1    0       1
                            1  0    0    0    1    0    0    0    1    0       1
                                                        1    0    0    0       1
1  1    1    1    1    1    1  1    1    1    1    0    1    1    1    1       1
Length: 784, dtype: int64

In [70]:
#Average linkage
cluster3 = AgglomerativeClustering(n_clusters=None, affinity='manhattan', linkage='average', distance_threshold = 1.0001)
d3 = cluster3.fit_predict(S)
d3

array([134, 134, 134, ..., 256, 312, 468], dtype=int64)

In [85]:
#Value counts
S.value_counts()

0  0.1  0.2  0.3  0.4  0.5  1  1.1  0.6  1.2  1.3  1.4  1.5  1.6  0.7  0.8
0  1    0    1    0    0    1  0    0    0    0    0    1    1    0    0      10
1  1    0    1    1    1    1  1    1    1    0    0    1    1    1    1       9
        1    1    0    0    1  1    0    1    0    1    1    1    1    1       8
0  1    0    0    0    1    1  1    0    1    0    1    0    0    0    1       8
1  0    0    1    1    0    0  0    1    1    0    0    1    0    0    1       7
                                                                              ..
0  1    0    1    1    1    0  1    0    0    1    0    1    1    1    0       1
                                                   1    1    0    1    0       1
                            1  0    0    0    1    0    0    0    1    0       1
                                                        1    0    0    0       1
1  1    1    1    1    1    1  1    1    1    1    0    1    1    1    1       1
Length: 784, dtype: int64

The value counts for the linkage methods appear to be the same.

### 5
Cluster the dataset again, this time using K-means clustering with the number of clusters set to the number you found in Q2. Create a bar plot for the size of the clusters. Compare with your plot in Q2, how do these results differ? Give an explanation for this difference.

In [72]:
#KMeans cluster
kmeans = KMeans(
   ...:     init="random",
   ...:     n_clusters=3,
   ...:     n_init=10,
   ...:     max_iter=300,
   ...:     random_state=42
   ...: )
kmeans.fit(S)

KMeans(init='random', n_clusters=3, random_state=42)

In [74]:
#KMeans inertia
kmeans.inertia_

3474.9299975751237

In [75]:
#KMeans cluster
kmeans.cluster_centers_

array([[0.2939759 , 0.72289157, 0.10361446, 0.30843373, 0.10843373,
        0.52289157, 0.7373494 , 0.71325301, 0.11084337, 0.45542169,
        0.3060241 , 0.67951807, 0.7060241 , 0.4939759 , 0.08915663,
        0.3253012 ],
       [0.70351759, 0.0879397 , 0.11557789, 0.71105528, 0.30904523,
        0.2839196 , 0.09798995, 0.09296482, 0.70854271, 0.89949749,
        0.44723618, 0.29648241, 0.5201005 , 0.51507538, 0.50251256,
        0.90201005],
       [0.47668394, 0.65025907, 0.52072539, 0.93005181, 0.48445596,
        0.69430052, 0.89119171, 0.90932642, 0.29015544, 0.69170984,
        0.51554404, 0.3134715 , 0.91968912, 0.72279793, 0.9119171 ,
        0.48445596]])